version: 2

models:
  - name: int_sales__margin
    description: margin calcultation per order line / product sale
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - Purchase_cost
            - date_date
            - revenue
            - quantity
  - name: int_orders__margin
    description: margin calcultation per order
    columns:
      - name: orders_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order
      - name: quantity
        description: sum of quantity per order
  - name: int_orders__operational
    description: operational margin calcultation per order
    columns:
      - name: operational_margin
        description: Operational margin = margin + shipping fee - log_cost - ship_cost
